# External libraries for visualization and rolling window calculation
library(ggplot2)
library(zoo)

# --- STEP 1: Global Data Structures ---
# Kyte-Doolittle hydrophobicity scale (extracted for modularity)
kyte_doolittle_scale <- c(
  I = 4.5, V = 4.2, L = 3.8, F = 2.8, C = 2.5,
  M = 1.9, A = 1.8, G = -0.4, T = -0.7, S = -0.8,
  W = -0.9, Y = -1.3, P = -1.6, H = -3.2, E = -3.5,
  Q = -3.5, D = -3.5, N = -3.5, K = -3.9, R = -4.5
)

# --- STEP 2: Main Function ---
analyze_protein <- function(sequence, window_size = 7, scale_dict = kyte_doolittle_scale) {
  
  # 1. String Handling and Noise Reduction
  clean_sequence <- gsub("[[:space:]]", "", sequence)
  clean_sequence <- toupper(clean_sequence)
  
  # Tokenization
  amino_acids <- strsplit(clean_sequence, split = "")[[1]]
  
  # Mathematical quantification of biological noise
  valid_aas <- sum(amino_acids %in% names(scale_dict))
  total_chars <- length(amino_acids)
  noise_percentage <- round(((total_chars - valid_aas) / total_chars) * 100, 2)
  
  # 2. The Engine: Vectorized Rolling Mean
  # Map sequence to numeric values using the provided dictionary
  numeric_values <- scale_dict[amino_acids]
  
  # Replace NA (invalid amino acids) with 0 to prevent breaking the calculation
  numeric_values[is.na(numeric_values)] <- 0
  
  # Vectorized rolling mean using zoo (align="left" matches the original starting coordinate logic)
  hydro_results <- zoo::rollmean(numeric_values, k = window_size, align = "left", fill = NA)
  
  # Remove the NA padding at the end generated by rollmean
  hydro_results <- hydro_results[!is.na(hydro_results)]
  num_windows <- length(hydro_results)
  
  # 3. Data Structuring
  results_table <- data.frame(
    Position = 1:num_windows,
    Target_Region = paste(1:num_windows, "to", (1:num_windows) + window_size - 1),
    Hydrophobicity = round(hydro_results, 2)
  )
  
  # Sort to extract the most thermodynamically viable targets (lowest hydrophobicity / most hydrophilic)
  best_targets <- head(results_table[order(results_table$Hydrophobicity), ], 3)
  target_report <- best_targets[, c("Target_Region", "Hydrophobicity")]
  
  # 4. Visualization with ggplot2
  plot <- ggplot(results_table, aes(x = Position, y = Hydrophobicity, color = Hydrophobicity)) +
    geom_line(aes(group = 1), size = 1.2) +
    # Kept the professional blue/red gradient, ensuring high contrast
    scale_color_gradient2(low = "#2166ac", mid = "#bababa", high = "#b2182b", 
                      midpoint = 0, name = "K-D Index") +
    geom_hline(yintercept = 0, color = "black", linetype = "dashed", alpha = 0.5) +
    theme_minimal() +
    labs(
      title = "Thermodynamic Profile of SIRT1 Enzyme",
      subtitle = paste("Parametric filter n =", window_size),
      x = "Coordinates (Window Start)",
      y = "Index (Kyte-Doolittle)"
    )
  
  dev.new() 
  print(plot)
  
  # 5. Console Output
  cat("\n==================================================\n")
  cat("                     REPORT\n")
  cat("==================================================\n")
  cat(sprintf("-> Quality Control: %s%% biological noise detected.\n", noise_percentage))
  cat("-> Top 3 target regions for synthetic editing:\n\n")
  print(target_report, row.names = FALSE)
  cat("==================================================\n\n")
}

# --- FINAL TEST ---
sirt1_gene <- "MADEAALALQPGGSPSAAGADREAASSPAGEPLRKRPRRDGPGLERSPGEPGGAAPEREVPAAARGCPGAAAAALWREAEAEAAAAGGEQEAQATAAAGEGDNGPGLQGPSREPPLADNLYDEDDDDEGEEEEEAAAAAIGYRDNLLFGDEIITNGFHSCESDEEDRASHASSSDWTPRPRIGPYTFVQQHLMIGTDPRTILKDLLPETIPPPELDDMTLWQIVINILSEPPKRKKRKDINTIEDAVKLLQECKKIIVLTGAGVSVSCGIPDFRSRDGIYARLAVDFPDLPDPQAMFDIEYFRKDPRPFFKFAKEIYPGQFQPSLCHKFIALSDKEGKLLRNYTQNIDTLEQVAGIQRIIQCHGSFATASCLICKYKVDCEAVRGDIFNQVVPRCPRCPADEPLAIMKPEIVFFGENLPEQFHRAMKYDKDEVDLLIVIGSSLKVRPVALIPSSIPHEVPQILINREPLPHLHFDVELLGDCDVIINELCHRLGGEYAKLCCNPVKLSEITEKPPRTQKELAYLSELPPTPLHVSEDSSSPERTSPPDSSVIVTLLDQAAKSNDDLDVSESKGCMEEKPQEVQTSRNVESIAEQMENPDLKNVGSSTGEKNERTSVAGTVRKCWPNRVAKEQISRRLDGNQYLFLPPNRYIFHGAEVYSDSEDDVLSSSSCGSNSDSGTCQSPSLEEPMEDESEIEEFYNGLEDEPDVPERAGGAGFGTDGDDQEAINEAISVKQEVTDMNYPSNKS"
analyze_protein(sequence = sirt1_gene, window_size = 7)
